### ISSUE TITLE
Cannot change error message for `test_object_after_expression`

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#12] opened 2016-05-31 21:16 UTC
@franciscastro can't seem to write his own error message for `test_object_after_expression`: setting `incorrect_msg` doesn't change anything. also, default message has a capital 'A' after the comma, which should be lower case (screenshot). this occurs in other cases also.

<img width="1272" alt="screen shot 2016-05-31 at 4 57 52 pm" src="https://cloud.githubusercontent.com/assets/4182382/15690820/561a8ff2-2753-11e6-991f-87425cfe820d.png">

**Comment by vincentvankrunkelsven** [comment] 2016-06-01 09:50
Can you be more specific on how in `test_object_after_expression()`, `incorrect_msg` doesn't work? It seems to work when I test it.
![image](https://cloud.githubusercontent.com/assets/2217728/15705205/8828ad4e-27ee-11e6-82cb-78077cb51aba.png)

source: https://github.com/vincentvankrunkelsven/user-defined-functions-mini-course/blob/master/chapter1.md#write-a-simple-function in the SCT

Btw: If you don't want the `In your definition of `shout()`, ...` part, you have to set `expand_message = False` in `test_function_definition()`.

**Comment by vincentvankrunkelsven** [comment] 2016-06-01 09:56
So I can't reproduce the error with `incorrect_msg`, the capitalised first letter is fixed on development.

**Comment by hugobowne** [comment] 2016-06-01 13:53
it's working now, thanks. @franciscastro thinks that his edits maybe weren't built. The capitalization is an issuie: should i leave it here or re-raise it?

**Comment by vincentvankrunkelsven** [comment] 2016-06-02 14:07
Fixed in #13 pull request

**Closed by vincentvankrunkelsven** 2016-06-02 14:07 UTC
Labels: bug
