### ISSUE TITLE
SCT somehow creates error when correct code submitted

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#10] opened 2016-05-27 16:05 UTC
In https://campus.datacamp.com/courses/1113/2464?ex=3 ,

when we submit the solution code, python throws an error. this did not happen when SCT wasn't present.

see screenshot:

<img width="1273" alt="screen shot 2016-05-27 at 11 57 10 am" src="https://cloud.githubusercontent.com/assets/4182382/15613779/497203b4-2403-11e6-8af2-9b54cdf0b59a.png">

**Comment by vincentvankrunkelsven** [comment] 2016-05-27 16:38
So these are issues of scoping. The problem is that `test_function()` and `test_object_after_expression()` will run parts of the code in the global scope, but `word` and `shout_word` are defined only in the function's scope. 

In `test_object_after_expression()` you can use the argument `context_vals` to work around this problem. To `context_vals` you can assign a list of values, which will be assigned to the variable in the context its surrounding test. If it's used within `test_function_definition()`, the context variables will be the arguments of the function. For example,

```
*** = solution
def shout(word):
    shout_word = word + '!!!'
```

```
*** =sct
test_function_definition('shout', arg_names = False, body = lambda: test_object_after_expression("shout_word", context_vals = ["shouting this"]))
```

This test will test the object `shout_word` after running through the body of `shout()` with its only argument, word, set to `"shouting this"`. Note that this test implies nothing about how you call the argument, you could call it `foo` instead of `word` and the test would still past.

You can also use `test_object_after_expression()` within a `test_for_loop()` for example, in this case the `context_vals` will be the values of the loop variable.

If you use `test_function()` will currently just run in the global scope, and there's no way to set the arguments when running the tests.

I'm thinking of ways to make this less complex and more intuitive.

**Comment by hugobowne** [comment] 2016-05-27 16:57
@vincentvankrunkelsven thank you! this workaround doesn't look as complex as some that were used during the dev of `testwhat` ;-)

@franciscastro  try this out (should work for both problems that we had) and we'll let @vincentvankrunkelsven know how it goes asap

**Comment by hugobowne** [comment] 2016-05-27 18:56
about to try to implement this now

**Comment by hugobowne** [comment] 2016-05-27 18:57
@franciscastro about to try this now

**Comment by hugobowne** [comment] 2016-05-27 18:58
won't take long

**Comment by franciscastro** [comment] 2016-05-27 19:14
It doesn't seem to work for cases when I have to test an object within a function definition, but the function does not have parameters.

![05-27-2016-test-function-in-def-error-5-1](https://cloud.githubusercontent.com/assets/1910413/15618730/b96dc5ee-241d-11e6-8543-5ecae7cec83d.PNG)

**Comment by hugobowne** [comment] 2016-05-27 21:02
@vincentvankrunkelsven the `context_vals` workaround doesn't seem to be working for us.

In the case that the function we're defining takes no arguments we have tried 

 - `context_vals = []` (then we get above error 'list index out of range')
- we have also tried along `context_vals` as a list of one element and in this case we get the 'not defined' error.

this occurs in https://campus.datacamp.com/courses/1113/2464?ex=3

Also, in https://campus.datacamp.com/courses/1113/2464?ex=4 , the function in which takes an argument, using `context_vals=["congratulations!!!"]` throws the not defined error. see screenshot.

any other workarounds?

It looks like @franciscastro 's SCTs are written correctly but maybe you want to take a quick look also

<img width="1268" alt="screen shot 2016-05-27 at 4 58 41 pm" src="https://cloud.githubusercontent.com/assets/4182382/15621104/952aac88-242c-11e6-8658-23eac54a0573.png">

**Comment by vincentvankrunkelsven** [comment] 2016-05-29 17:11
Seems like it doesn't work as I expected, I'll have a look and it'll be fixed in the next patch. That will probably be put live Monday evening my time, so that would be Monday around noon for you.

**Comment by vincentvankrunkelsven** [comment] 2016-05-30 17:10
Ok so I had a look at your problems:

- For exercise 3: setting `context_vals = []` caused an error. However for the effect you desire, just don't define `context_vals`, it will be set to `None` by default, and this will provide the correct behaviour. I added a check in a new version, that causes `[]` to be treated like `None` for the `context_vals` argument.
- For exercise 4: the problem here is not caused by `test_object_after_expression()`, but rather by `test_function()` in your fourth `test_function_definition()`. As I mentioned before, `test_function()` is by design only capable of testing arguments in the global scope. (It doesn't have something like `context_vals`, I think it maybe should). You can check whether the function `print()` is used by using `test_function('print', args=[])` and you can check if the correct output is given in the function definition by using: `outputs` of the `test_function_definition()` function. I'm working on a better way of handling the scopes, so `test_function()` can be used properly within other test functions.

**Comment by hugobowne** [comment] 2016-05-31 13:44
@vincentvankrunkelsven neither of these seem to be working still. perhaps you and I should speak for 5min and/or you could write an example SCT that you think should work?

**Comment by vincentvankrunkelsven** [comment] 2016-06-02 14:08
They are fixed

**Closed by vincentvankrunkelsven** 2016-06-02 14:08 UTC
Labels: question
