### ISSUE TITLE
Improve messages when using context_vals

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#121] opened 2016-10-10 14:40 UTC
@hugobowne pointed out last week that the default message for test_\* functions w/context_vals is confusing. The message depends on the context_val that was sent, but students won't know what that value actually was.

(will need to wait until refactoring message to take a pass at this)

**Comment by filipsch** [comment] 2018-07-30 09:08
Duplicate of #317

**Closed by filipsch** 2018-07-30 09:08 UTC
Labels: enhancement, messages
